/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetable_integrated_spm.swing.sessions;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import timetable_integrated_spm.swing.Subject.HomeSubjects;
import timetable_integrated_spm.swing.lecturerDetails.AddLecturer;
import timetable_integrated_spm.swing.lecturerDetails.HomeLecturers;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author  Jayagoda N.M.  -  IT17184304
 */
public class AddSession extends javax.swing.JFrame {

    
    private Connection connection;
    private Statement statement;
    private PreparedStatement preparedStmt;
    String lecturers, tag, subject_name, subject_code, student_group_id;
    int duration, number_of_students;
    public static ArrayList<String> session_string;
    private static String session_val = null;
    /**
     * Creates new form AddSession
     */
    public AddSession() {
        initComponents();
        dbconnect();
        AutoCompleteDecorator.decorate(input_lecturer_combobox);
        AutoCompleteDecorator.decorate(input_student_group);
        AutoCompleteDecorator.decorate(input_subject_combobox);
        FillComboBox();
        
    }
    
    private void dbconnect(){
        final String DRIVER = "org.apache.derby.jdbc.EmbeddedDriver";
        final String JDBC_URL = "jdbc:derby:unidb;create=true";
        
        try {
            Class.forName(DRIVER);
            connection = DriverManager.getConnection(JDBC_URL);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddLecturer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddLecturer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }  
        
    }
    
    public void FillComboBox(){
        try {
            String lecturerQuery = "SELECT lecturer_fname, lecturer_lname FROM lecturer";
            String tagsQuery = "SELECT tag FROM tags";
            String studentsQuery = "SELECT groupId FROM students";
            String subjectsQuery = "SELECT subject_name FROM subject";
            
            statement = connection.createStatement();
            
            ResultSet rsl = statement.executeQuery(lecturerQuery);
            while(rsl.next()){
                this.input_lecturer_combobox.addItem(rsl.getString(1).toString() + " " + rsl.getString(2).toString());
            }
            this.input_lecturer_combobox.setMaximumRowCount(8);
            
            
            ResultSet rst = statement.executeQuery(tagsQuery);
            while(rst.next()){
                this.input_tag_combobox.addItem(rst.getString(1));
            }
            
           ResultSet rs_subj = statement.executeQuery(subjectsQuery);
           while(rs_subj.next()){
               this.input_subject_combobox.addItem(rs_subj.getString(1));
           }
           this.input_tag_combobox.setMaximumRowCount(6);
            
           ResultSet rs_stud = statement.executeQuery(studentsQuery);
           while(rs_stud.next()){
               this.input_student_group.addItem(rs_stud.getString(1));
           }
           this.input_student_group.setMaximumRowCount(5);
           
           
           
        } catch (SQLException e) {
            System.err.println("Exception in lecturer_name_ComboBox : AddSessions");
            Logger.getLogger(AddLecturer.class.getName()).log(Level.SEVERE, null, e);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btn_statisticsTab = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_studentTab = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btn_subjectTab = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btn_workingDaysTab = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btn_locationTab = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_lecturerTab = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        btn_sessionTab = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_create_session = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        input_lecturer_combobox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        add_lecturer_btn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lecturers_session_label = new javax.swing.JTextArea();
        lecturer_title_combobox = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        input_student_group = new javax.swing.JComboBox<>();
        input_number_of_students = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        input_tag_combobox = new javax.swing.JComboBox<>();
        input_subject_combobox = new javax.swing.JComboBox<>();
        duration_spinner = new javax.swing.JSpinner();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1600, 1000));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/codejava/images/icons8-group-of-projects-50.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 860, -1, -1));

        btn_statisticsTab.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        btn_statisticsTab.setText("Statistics");
        btn_statisticsTab.setFocusPainted(false);
        btn_statisticsTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_statisticsTabActionPerformed(evt);
            }
        });
        jPanel1.add(btn_statisticsTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 840, 420, 90));

        jLabel4.setBackground(new java.awt.Color(153, 102, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/codejava/images/icons8-lecturer-50.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 50, 60));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/codejava/images/icons8-student-registration-50.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 590, -1, -1));

        btn_studentTab.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        btn_studentTab.setText("Students");
        btn_studentTab.setFocusPainted(false);
        btn_studentTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_studentTabActionPerformed(evt);
            }
        });
        jPanel1.add(btn_studentTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 420, 90));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/codejava/images/icons8-love-book-50.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        btn_subjectTab.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        btn_subjectTab.setText("Subjects");
        btn_subjectTab.setFocusPainted(false);
        btn_subjectTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_subjectTabActionPerformed(evt);
            }
        });
        jPanel1.add(btn_subjectTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 420, 90));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/codejava/images/icons8-calendar-10-50.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 680, -1, -1));

        btn_workingDaysTab.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        btn_workingDaysTab.setText("       Working days");
        btn_workingDaysTab.setFocusPainted(false);
        btn_workingDaysTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_workingDaysTabActionPerformed(evt);
            }
        });
        jPanel1.add(btn_workingDaysTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 420, 90));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/codejava/images/icons8-location-64.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 770, -1, 60));

        btn_locationTab.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        btn_locationTab.setText("Location");
        btn_locationTab.setFocusPainted(false);
        btn_locationTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_locationTabActionPerformed(evt);
            }
        });
        jPanel1.add(btn_locationTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 750, 420, 90));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(177, 122, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DASHBOARD");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 200, 130));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/codejava/images/icons8-home-50.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 70, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 420, 130));

        btn_lecturerTab.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        btn_lecturerTab.setText("Lectures");
        btn_lecturerTab.setFocusPainted(false);
        btn_lecturerTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lecturerTabActionPerformed(evt);
            }
        });
        jPanel1.add(btn_lecturerTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 420, 90));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/codejava/images/icons8-stopwatch-64.png"))); // NOI18N
        jLabel17.setText("jLabel1");
        jLabel17.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 60, 60));

        btn_sessionTab.setBackground(new java.awt.Color(255, 51, 102));
        btn_sessionTab.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        btn_sessionTab.setText("Sessions");
        btn_sessionTab.setFocusPainted(false);
        btn_sessionTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sessionTabActionPerformed(evt);
            }
        });
        jPanel1.add(btn_sessionTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 420, 90));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 1000));

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 32)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SLIIT - Timetable Management System ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(289, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 1230, -1));

        btn_create_session.setBackground(new java.awt.Color(0, 153, 51));
        btn_create_session.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_create_session.setForeground(new java.awt.Color(255, 255, 255));
        btn_create_session.setText("Create Session");
        btn_create_session.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_create_sessionActionPerformed(evt);
            }
        });
        jPanel3.add(btn_create_session, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 920, 200, 50));

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/codejava/images/icons8-back-40.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 60, 60));

        jLabel1.setBackground(new java.awt.Color(255, 153, 0));
        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Select the relevant Lecturer(s)");
        jLabel1.setOpaque(true);
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 379, -1));

        input_lecturer_combobox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Added Lecturer(s) for the Session");

        add_lecturer_btn.setBackground(new java.awt.Color(102, 204, 0));
        add_lecturer_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/codejava/images/icons8-plus-math-24.png"))); // NOI18N
        add_lecturer_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_lecturer_btnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Enter Lecturer Name ");

        lecturers_session_label.setColumns(20);
        lecturers_session_label.setRows(5);
        jScrollPane2.setViewportView(lecturers_session_label);

        lecturer_title_combobox.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lecturer_title_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dr.", "Mr.", "Ms.", "Mrs.", "Miss." }));
        lecturer_title_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecturer_title_comboboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lecturer_title_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_lecturer_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(add_lecturer_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(199, 199, 199))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(input_lecturer_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lecturer_title_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(add_lecturer_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 930, 190));

        jLabel28.setBackground(new java.awt.Color(255, 153, 0));
        jLabel28.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 51));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Select Student Group and other details");
        jLabel28.setOpaque(true);
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 710, 379, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Number of students ");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("Select Student Group / Sub-group");

        input_number_of_students.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_number_of_studentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_student_group, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(259, 259, 259))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(input_number_of_students, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input_student_group, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input_number_of_students, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 720, 930, 150));

        jLabel19.setBackground(new java.awt.Color(255, 153, 0));
        jLabel19.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Select Tag and Subject details");
        jLabel19.setOpaque(true);
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 460, 379, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setText("Enter Subject name ");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setText("Select Tag");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel26.setText("Duration");

        input_subject_combobox.setToolTipText("");
        input_subject_combobox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                input_subject_comboboxItemStateChanged(evt);
            }
        });
        input_subject_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_subject_comboboxActionPerformed(evt);
            }
        });
        input_subject_combobox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                input_subject_comboboxKeyReleased(evt);
            }
        });

        duration_spinner.setEditor(new javax.swing.JSpinner.NumberEditor(duration_spinner, ""));

        jLabel27.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel27.setText("hour(s)");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(duration_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(input_subject_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(input_tag_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(264, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input_tag_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input_subject_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(duration_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 930, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_create_sessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_create_sessionActionPerformed
        // TODO add your handling code here:
        lecturers = lecturers_session_label.getText().toString();
        tag = input_tag_combobox.getSelectedItem().toString();
        subject_name = input_subject_combobox.getSelectedItem().toString();
        student_group_id = input_student_group.getSelectedItem().toString();
         
        try {
            duration = Integer.parseInt(duration_spinner.getValue().toString());
            number_of_students = Integer.parseInt(input_number_of_students.getText().toString());
        } catch (NumberFormatException ex) {
            System.err.println("Got a Number Format Exception!");
            System.err.println(ex.getMessage());
        }
        
        String query_subject_code = "select subject_code from subject where subject_name = ?";
        
        try {
            preparedStmt = connection.prepareStatement(query_subject_code);
            preparedStmt.setString( 1, subject_name);
            
            ResultSet rs_subjcode = preparedStmt.executeQuery();
            while(rs_subjcode.next()){
                subject_code = rs_subjcode.getString(1);
            }
        } catch (SQLException ex) {
            System.err.println("Exception in retrieving subject code : " + ex.getMessage());
            Logger.getLogger(AddSession.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String query = "insert into sessions( lecturers, tag, subject_name, subject_code, student_group_id, duration, number_of_students) values( ?, ?, ?, ?, ?, ?, ?)";
        
        if (!lecturers.isEmpty() && !tag.isEmpty() && !subject_name.isEmpty() && !student_group_id.isEmpty() && !duration_spinner.getValue().toString().isEmpty() && !input_number_of_students.getText().toString().isEmpty()) {
            if (duration > 0 && number_of_students > 0 && isNumber(duration_spinner.getValue().toString()) && isNumber(input_number_of_students.getText().toString())) {
                try {
                    preparedStmt = connection.prepareStatement(query);
                    preparedStmt.setString(1, lecturers);
                    preparedStmt.setString(2, tag);
                    preparedStmt.setString(3, subject_name);
                    preparedStmt.setString(4, subject_code);
                    preparedStmt.setString(5, student_group_id);
                    preparedStmt.setInt(6, duration);
                    preparedStmt.setInt(7, number_of_students);

                    // execute the preparedstatement
                    preparedStmt.execute();

                    lecturers_session_label.setText("");
                    duration_spinner.setValue(Integer.valueOf(0));
                    input_number_of_students.setText("");

                    JOptionPane.showMessageDialog(null, "Record inserted successfully to the Database. \n Thank You!");

                } catch (SQLException ex) {
                    Logger.getLogger(AddSession.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Something went wrong! Please try again.");
                    System.err.println("Got an exception!");
                    System.err.println(ex.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(null, "Error! \n Invalid input", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "One or more fields are Empty!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
        
//        System.out.println("Lecturers for the Session : " + lecturers_session_label.getText().toString());
//        System.out.println("Spinner value duration : " + duration_spinner.getValue().toString()); 
//        System.out.println("Tag for the Session : " + input_tag_combobox.getSelectedItem().toString());
//        System.out.println("Subject Name for the Session : " + input_subject_combobox.getSelectedItem().toString());
//        System.out.println("Student group for the Session : " + input_student_group.getSelectedItem().toString());
//        System.out.println("Number of Students : " + input_number_of_students.getText().toString());
        
        String sessionString = lecturers + "\n" + subject_name + " (" + subject_code + ")" + "\n" 
                + tag + "\n" + student_group_id
                + "\n" + number_of_students + "(" + duration + ")"; 
        
        System.out.println("Session string :"  + sessionString);
        
        try {
            statement = connection.createStatement();
            String querySession = "insert into sessionsValues values('"+ sessionString +"')";
            statement.execute(querySession);
            System.out.println("Session record inserted successfully");
//        Session.session_string_arr.add(sessionString);
//        System.out.println("Session String ArrayList : " + Session.session_string_arr.size());
        } catch (SQLException ex) {
            Logger.getLogger(AddSession.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_create_sessionActionPerformed

    /**
     * 
     * 
     * Check whether a input value is a number ( numeric value)
     * @param input
     * @return boolean 
     */
    public boolean isNumber(String input){
        boolean res = false;
        int inputInteger = 0;
        try {
            inputInteger = Integer.parseInt(input);
            res = true;
        } catch (NumberFormatException ex) {
            return false;
            //System.err.println("Input value is not an Integer !");
        }
        return res;
    }
    
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        HomeSessions wnd_homeLecturer = new HomeSessions();
        wnd_homeLecturer.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btn_statisticsTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_statisticsTabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_statisticsTabActionPerformed

    private void btn_studentTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_studentTabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_studentTabActionPerformed

    private void btn_subjectTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_subjectTabActionPerformed
        // TODO add your handling code here:
        this.dispose();
        HomeSubjects wnd_homeSubjects = new HomeSubjects();
        wnd_homeSubjects.setVisible(true);
    }//GEN-LAST:event_btn_subjectTabActionPerformed

    private void btn_workingDaysTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_workingDaysTabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_workingDaysTabActionPerformed

    private void btn_locationTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_locationTabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_locationTabActionPerformed

    private void btn_lecturerTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lecturerTabActionPerformed
        // TODO add your handling code here:
        this.dispose();
        HomeLecturers wnd_homeLecturer = new HomeLecturers();
        wnd_homeLecturer.setVisible(true);
    }//GEN-LAST:event_btn_lecturerTabActionPerformed

    private void add_lecturer_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_lecturer_btnActionPerformed
        // TODO add your handling code here:
        String title_lecturer = this.lecturer_title_combobox.getSelectedItem().toString();
        String curLecturer = title_lecturer + " " +  this.input_lecturer_combobox.getSelectedItem().toString();
        
//        ArrayList<String> lecturers_arrl = new ArrayList<String>();
//        lecturers_arrl.add(curLecturer);
        
        if(this.lecturers_session_label.getText().isEmpty()){
            this.lecturers_session_label.setText(curLecturer);
        }else{
            String curSelected_lecturers = this.lecturers_session_label.getText().toString() + ", " + curLecturer;
            this.lecturers_session_label.setText(curSelected_lecturers); 
        }
        
    }//GEN-LAST:event_add_lecturer_btnActionPerformed

    private void btn_sessionTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sessionTabActionPerformed
        // TODO add your handling code here:
        this.dispose();
        HomeSessions wnd_homeSessions = new HomeSessions();
        wnd_homeSessions.setVisible(true);
    }//GEN-LAST:event_btn_sessionTabActionPerformed

    private void input_number_of_studentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_number_of_studentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_number_of_studentsActionPerformed

    private void input_subject_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_subject_comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_subject_comboboxActionPerformed

    private void input_subject_comboboxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_subject_comboboxKeyReleased

    }//GEN-LAST:event_input_subject_comboboxKeyReleased

    private void input_subject_comboboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_input_subject_comboboxItemStateChanged
        // TODO add your handling code here : 
    }//GEN-LAST:event_input_subject_comboboxItemStateChanged

    private void lecturer_title_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecturer_title_comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lecturer_title_comboboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        
//        session_string.add(session_val);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddSession().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_lecturer_btn;
    private javax.swing.JButton btn_create_session;
    private javax.swing.JButton btn_lecturerTab;
    private javax.swing.JButton btn_locationTab;
    private javax.swing.JButton btn_sessionTab;
    private javax.swing.JButton btn_statisticsTab;
    private javax.swing.JButton btn_studentTab;
    private javax.swing.JButton btn_subjectTab;
    private javax.swing.JButton btn_workingDaysTab;
    private javax.swing.JSpinner duration_spinner;
    private javax.swing.JComboBox<String> input_lecturer_combobox;
    private javax.swing.JTextField input_number_of_students;
    private javax.swing.JComboBox<String> input_student_group;
    private javax.swing.JComboBox<String> input_subject_combobox;
    private javax.swing.JComboBox<String> input_tag_combobox;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> lecturer_title_combobox;
    private javax.swing.JTextArea lecturers_session_label;
    // End of variables declaration//GEN-END:variables
}
